# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  config,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelParams = [ "acpi_enforce_resources=lax" ];
  boot.kernelModules = [
    "kvm-amd"
    "coretemp"
    "it87"
  ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ it87 ];
  boot.extraModprobeConfig = ''
    options it87 force_id=0x8689
  '';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c9f78218-f571-4343-bb91-3ce4d990a444";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-328fac88-2d3c-4307-8e59-9f17972b163f".device = "/dev/disk/by-uuid/328fac88-2d3c-4307-8e59-9f17972b163f";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/75D6-B7A8";
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/ccc6ef7e-50f8-4092-bee7-6dcac6a49e99"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp14s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp15s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
