[default_apps]
calendar_client = "thunderbird" # For fetching event tile data
terminal = "kitty"              # Used to start applications
browser = "firefox"             # Used for web searches

[units]
lengths = "m"
weights = "Kg"
volumes = "L"
temperatures = "ºC"
currency = "€"

[debug]
try_suppress_errors = false  # Disables the error screen for errors
try_suppress_warnings = true # Disables the error screen for warnings

[appearance]
width = 900 # Sets the width of the main window
height = 593 # Sets the height of the main window
gsk_renderer = "cairo" # Sets the rendering engine. [ngl, cairo, ]
recolor_icons = false # If set to true, uses the [icon-name]-symbolic icons
icon_paths = [
  "~/.config/sherlock/icons",
] # Sets where the application should look for custom icons
icon_size = 22 # Sets the icon size for the tiles

[behavior]
daemonize = false # Enables deamon mode
animation = true  # Enables startup animations

[caching]
enable = false
cache = "~/.cache/sherlock_desktop_cache.json" # Sets the location for caching files

[status_bar]
enable = true

[files]
fallback = "~/.config/sherlock/fallback.json"
css = "~/.config/sherlock/main.css"
alias = "~/.config/sherlock/sherlock_alias.json"
ignore = "~/.config/sherlock/sherlockignore"
actions = "~/.config/sherlock/sherlock_actions.json"
