import decman
from decman import File, Directory

# System packages
decman.packages += [
    # 'nerd-fonts',
    'amd-ucode',
    'ark',
    'bacon',
    'base',
    'base-devel',
    'bluetui',
    'bluez',
    'bluez-utils',
    'btrfs-progs',
    'cmake',
    'cpio',
    'cryptsetup',
    'efibootmgr',
    'ffmpegthumbs',
    'gamemode',
    'grub',
    'grub-btrfs',
    'inotify-tools',
    'kitty',
    'lib32-gamemode',
    'linux',
    'linux-firmware',
    'linux-headers',
    'linux-lts',
    'linux-lts-headers',
    'ly',
    'man-db',
    'neofetch',
    'networkmanager',
    'noto-fonts',
    'noto-fonts-cjk',
    'noto-fonts-emoji',
    'noto-fonts-extra',
    'openssh',
    'pipewire',
    'pipewire-alsa',
    'pipewire-pulse',
    'snapper',
    'stow',
    'sudo',
    'timeshift',
    'ttf-font-awesome',
    'uwsm',
    'vim',
    'zellij',
]

# Desktop Only
decman.packages += [
    'lib32-nvidia-utils',
    'nvidia-open-lts',
    'nvidia-utils',
]

# Desktop Environment
decman.packages += [
    'archlinux-xdg-menu',
    'brightnessctl',
    'dunst',
    'gammastep',
    'hypridle',
    'hyprland',
    'hyprlock',
    'hyprpicker',
    'hyprpolkitagent',
    'hyprsunset',
    'libva-nvidia-driver',
    'waybar',
    'wofi',
    'xdg-desktop-portal-hyprland',
]

# CLI Tools
decman.packages += [
    'chezmoi',
    'fzf',
    'fzf-tab-git',
    'git',
    'github-cli',
    'lazygit',
    'maven',
    'neofetch',
    'neovim',
    'net-tools',
    'protonvpn-cli-community',
    'starship',
    'tldr',
    'tree',
    'typst',
    'valgrind',
    'yazi',
    'yt-dlp',
    'zoxide',
    'zsh',
    'zsh-autosuggestions',
    'zsh-completions',
    'zsh-syntax-highlighting',
    'zsh-vi-mode',
]

# Programs
decman.packages += [
    'audacity',
    'blender',
    'chromium',
    'discord',
    'dolphin',
    'dotnet-runtime-8.0',
    'drawio-desktop',
    'eog',
    'firefox',
    'flatpak',
    'gimp',
    'gnome-keyring',
    'godot-mono',
    'gvfs',
    'inkscape',
    'kdeconnect',
    'kdegraphics-thumbnailers',
    'kdenlive',
    'keepassxc',
    'kolourpaint',
    'lutris',
    'mission-center',
    'mpv',
    'nautilus',
    'nemo',
    'obfuscate',
    'obsidian',
    'pavucontrol',
    'pdfarranger',
    'pdfpc',
    'prismlauncher',
    'protonmail-bridge',
    'rustlings',
    'scrcpy',
    'signal-desktop',
    'steam',
    'syncthing',
    'thunar',
    'thunderbird',
    'vlc',
    'xournalpp',
]

decman.aur_packages += [
    # 'footage', -- broken, use flatpak instead
    'anki-bin',
    'anyrun-git',
    'bazecor',
    'betterdiscordctl',
    'denaro',
    'discover-overlay',
    'gpu-screen-recorder-gtk',
    'heroic-games-launcher-bin',
    'hyprshot',
    'librewolf-bin',
    'localsend-bin',
    'numbat',
    'onlyoffice-bin',
    'pandoc-bin',
    'paru',
    'protonup-qt',
    'r2modman-bin',
    'ryujinx',
    'timeshift-autosnap',
    'vintagestory',
    'yay',
    'yt-dlg',
    'zapzap',
]

decman.ignored_packages += [
    'decman-git',
]
