# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, config, modulesPath, ... }:

{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-amd" ];
	boot.extraModulePackages = [ ];

	fileSystems."/" =
	{ device = "/dev/disk/by-uuid/8e4d8a26-571f-4a8c-8dda-58d4be3a05ea";
		fsType = "ext4";
	};

	boot.initrd.luks.devices."luks-835cb89f-4664-48a3-be67-c90600d858a1".device = "/dev/disk/by-uuid/835cb89f-4664-48a3-be67-c90600d858a1";

	fileSystems."/boot" =
	{ device = "/dev/disk/by-uuid/42DD-C4E0";
		fsType = "vfat";
	};

	swapDevices =
		[ { device = "/dev/disk/by-uuid/d683e700-af7f-43c5-81c3-ac038ec753f9"; }
		];

# Enables DHCP on each ethernet and wireless interface. In case of scripted networking
# (the default) this is the recommended approach. When using systemd-networkd it's
# still possible to use this option, but it's recommended to use it in conjunction
# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
		networking.useDHCP = lib.mkDefault true;
# networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

		nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
		hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
